#!/usr/bin/env bash

set -euo pipefail

scad=$1
num_frames=50
start_angle=0
size="256,256"

# Temporary directory (and cleanup).
tempdir=$(mktemp -d)
trap 'rm -rf "$tempdir"' EXIT

filenames=()
cameras=()

for i in $(seq 1 "${num_frames}"); do
  angle=$(((start_angle - (i * 360 / num_frames)) % 360))
  printf -v outfile '%s/frame_%05d.png' "${tempdir}" "$i"
  translate="0,0,0"
  rot="${angle},0.0,180.0"
  dist=100

  filenames+=("${outfile}")
  cameras+=("${translate},${rot},${dist}")
done

parallel \
  --bar \
  --jobs '85%' \
  nice \
  openscad \
  "${scad}" \
  "--quiet" \
  "--enable=fast-csg" \
  "--o={1}" \
  "--imgsize=$size" \
  "--render" \
  "--colorscheme=Tomorrow" \
  "--camera={2}" \
  ::: "${filenames[@]}" \
  :::+ "${cameras[@]}"

magick \
  convert \
  "${tempdir}/frame_*.png" \
  -set delay 1x15 \
  "${scad/%.scad/.gif}"

# EOF
