name: "Update Gallery"

on:
  workflow_dispatch:
  push:
    paths:
      - "**.scad"
      - ".github/workflows/openscad.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make directory
        run: mkdir -p ./gallery

      - name: Create gallery
        uses: eXpire163/openscad-actions@main
        with:
          scad_file: ./
          output_file: ./gallery
          target_format_for_bulk: png

      - uses: EndBug/add-and-commit@v9
        with:
          add: ./gallery
          default_author: github_actions
# EOF
