name: "Update Gallery"

on:
  workflow_dispatch:
  push:
    paths:
      - "**.scad"
      - ".github/workflows/openscad.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap
        run: |
          set -eux
          script/bootstrap --yes
          # setup xvfb for headless mode without xServer present on linux
          # https://github.com/openscad/openscad/issues/1798
          sudo apt install -y xvfb

      - name: Make gallery
        run: |
          set -eux
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          make --jobs="$(nproc)" all

      - uses: EndBug/add-and-commit@v9
        with:
          add: ./gallery
          default_author: github_actions
# EOF
