name: "Update Gallery"

on:
  workflow_dispatch:
  push:
    paths:
      - "**.scad"
      - ".github/workflows/openscad.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make directory
        run: mkdir -p ./gallery

      - name: Copy .scad files
        run: cp -v *.scad ./gallery/

      - name: Create .stl files
        uses: eXpire163/openscad-actions@main
        with:
          scad_file: ./gallery
          output_file: ./gallery
          target_format_for_bulk: stl

      - name: Create gallery
        uses: eXpire163/openscad-actions@main
        with:
          scad_file: ./gallery
          output_file: ./gallery
          target_format_for_bulk: png

      - name: Repair README
        run: perl -pi -e 's!\.scad([\])])!.stl\1!g; s!\(\./gallery/!(!g;' gallery/README.md

      - name: Remove copied .scad files
        run: rm -v ./gallery/*.scad

      - uses: EndBug/add-and-commit@v9
        with:
          add: ./gallery
          default_author: github_actions
# EOF
