name: "Update Gallery"

on:
  workflow_dispatch:
  push:
    paths:
      - "**.scad"
      - ".github/workflows/openscad.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap
        run: script/bootstrap --yes

      - name: Make gallery
        run: make all

      - uses: EndBug/add-and-commit@v9
        with:
          add: ./gallery
          default_author: github_actions
# EOF
